FROM hardikdocker/solrcloud-zookeeper-docker
RUN\
	touch /zk-data/myid &&\
	echo 3 > /zk-data/myid &&\
	touch start.sh &&\
	echo "#!/usr/bin/env bash" >> start.sh &&\
	echo "./zk/bin/zkServer.sh start" >> start.sh &&\
	echo "./solr/bin/solr -cloud -z zoo1:2181,zoo2:2181,zoo3:2181 -s /solr-data" >> start.sh &&\
	echo "monit -I" >> start.sh &&\
	chmod 755 start.sh
CMD	/bin/bash
