FROM ubuntu
MAINTAINER hardikgw@gmail.com
ENV\
	ES_VER=2.3.4 \
	KB_VER=4.5.3 \
	FD_VER=3.4.8
COPY start-es-kb.sh /start.sh
RUN\
	apt-get update &&\
	apt-get install -y vim curl wget nodejs default-jdk lsof ntp &&\
	apt-get update &&\
	apt-get clean &&\
	wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/$ES_VER/elasticsearch-$ES_VER.tar.gz &&\
	tar xzvf elasticsearch-$ES_VER.tar.gz &&\
	ln -s elasticsearch-$ES_VER es &&\
	mkdir es-data &&\
	wget https://download.elastic.co/kibana/kibana/kibana-$KB_VER-linux-x64.tar.gz &&\
	tar xzvf kibana-$KB_VER-linux-x64.tar.gz &&\
	ln -s kibana-$KB_VER-linux-x64 kb &&\
	chmod 755 start.sh
EXPOSE 5601 9200 9300