FROM hardikdocker/solrcloud-zookeeper-docker
RUN\
	touch /zk-data/myid &&\
	echo 2 > /zk-data/myid &&\
	echo "server.1=zoo1:2888:3888" >> /zk/conf/zoo.cfg &&\
	echo "server.2=zoo2:2888:3888" >> /zk/conf/zoo.cfg &&\
	echo "server.3=zoo3:2888:3888" >> /zk/conf/zoo.cfg &&\
	touch start.sh &&\
	echo "#!/usr/bin/env bash" >> start.sh &&\
	echo "./zk/bin/zkServer.sh start" >> start.sh &&\
	echo "./solr/bin/solr stop" >> start.sh &&\
	echo "./solr/bin/solr -cloud -z zoo1:2181,zoo2:2181,zoo3:2181 -s /solr-data" >> start.sh &&\
	echo "monit -I" >> start.sh &&\
	chmod 755 start.sh
CMD	/bin/bash
