FROM ubuntu
RUN\
	apt-get update &&\
	apt-get install -y curl &&\
	curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add - &&\
	echo "deb http://packages.treasuredata.com/2/ubuntu/xenial/ xenial contrib" > /etc/apt/sources.list.d/treasure-data.list &&\
	apt-get update &&\
	apt-get install -y --force-yes td-agent