FROM hardikdocker/solrcloud-zookeeper-docker
CMD echo $ZKID >> /zk-data/myid && ./zk/bin/zkServer.sh start-foreground && ./solr/bin/solr -cloud -z solr-zk-1:2181,solr-zk-2:2181,solr-zk-3:2181 -s /solr-data && /bin/sh
